Improvements
Improved exec_dir detection
Allow use of local bash-functions for developement purposes

diff --git a/setup b/setup
--- a/setup
+++ b/setup
@@ -4,20 +4,34 @@
 
 ### Set bash environment error management
 
-set -e
-set -u
+set -eu
 
-### Source local functions file
+### Add padding to output
 
 echo
-source_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
 
-if [[ "$source_dir" == */tools ]]
+### Determine script execution directory, install directory, and source local functions file
+
+exec_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
+
+exec_dir_trim_2="$( echo ${exec_dir} | cut -f 1,2,3 -d'/')"
+exec_dir_trim_3="$( echo ${exec_dir} | cut -f 1,2,3,4 -d'/')"
+
+if [ -f "${exec_dir_trim_2}/functions" ]
 then
-        source_dir="${source_dir%/tools}"
+	exec_dir_root="${exec_dir_trim_2}"
+else
+	if [ -f "${exec_dir_trim_3}/functions" ]
+	then
+		exec_dir_root="${exec_dir_trim_3}"
+	else
+		echo "Functions file not found in any second or third level parent directory of: | $exec_dir |"
+		echo
+        exit 1
+	fi
 fi
 
-. "$source_dir/functions"
+. "$exec_dir_root/functions"
 
 ### Check for root user runtime
 
@@ -25,10 +39,14 @@ check_root
 
 ### Download and source openspace functions file
 
-while getopts ":be" arguments; do
+while getopts ":ble" arguments; do
     case $arguments in
-        b)	export bleeding_edge_bf="-b"
+        b)	export custom_bf="-b"
         echo "Using bleeding-edge bash-functions as per | -b |."
+        echo
+        ;;
+        l)	export custom_bf="-l"
+        echo "Disabling bash-functions download and using local version as per | -l |."
         echo
         ;;
         e)	export bleeding_edge_rc="-e"
@@ -44,7 +62,13 @@ done
 
 OPTIND=1
 
-download_os_functions "${bleeding_edge_bf-}"
+if [ ! "${custom_bf-null}" = "-l" ]
+then
+
+    download_os_functions "${custom_bf-}"
+
+fi
+
 source_os_functions
 
 ### Define formatting
